language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
    - /^greenkeeper/.*$/
install:
  - npm ci
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master
# keep the npm cache around to speed up installs
cache:
  directories:
    - '$HOME/.npm'
